# Generated by Django 4.1.7 on 2023-04-08 16:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('mobile', models.IntegerField()),
                ('textarea', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Not Found', max_length=100)),
                ('budget', models.BigIntegerField(default=-1)),
                ('genre', models.CharField(default='fantasy', max_length=2000)),
                ('language', models.CharField(default='en', max_length=100)),
                ('overview', models.CharField(default='not found', max_length=5000)),
                ('release', models.CharField(default='released', max_length=20)),
                ('revenue', models.BigIntegerField(default=-1)),
                ('duration', models.FloatField(default=-1)),
                ('tagline', models.CharField(default='not found', max_length=200)),
                ('rating', models.FloatField(default=5)),
                ('t_rating', models.IntegerField(default=10000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField(default=0)),
                ('email', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=5000)),
                ('movieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.movie')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
