# Generated by Django 4.1.7 on 2023-04-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_movie_id_alter_movie_t_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.IntegerField(default=426, editable=False, primary_key=True, serialize=False),
        ),
    ]
