# Generated by Django 4.1.7 on 2023-04-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.CharField(default='not fount', max_length=1000),
        ),
    ]
